<?
$MESS["MAIN_AGENT_EDIT_PAGE_TITLE"] = "الوكيل ##ID#";
$MESS["MAIN_AGENT_NEW_PAGE_TITLE"] = "وكيل جديد";
$MESS["MAIN_AGENT_TAB"] = "الوكيل";
$MESS["MAIN_AGENT_TAB_TITLE"] = "المعلمات";
$MESS["MAIN_AGENT_LAST_EXEC"] = "تاريخ آخر تشغيل:";
$MESS["MAIN_AGENT_NEXT_EXEC"] = "تاريخ التشغيل التالي:";
$MESS["MAIN_AGENT_ACTIVE"] = "نشط";
$MESS["MAIN_AGENT_NAME"] = "وظيفة الوكيل:";
$MESS["MAIN_AGENT_MODULE_ID"] = "الموديول:";
$MESS["MAIN_AGENT_USER_ID"] = "معرف المستخدم:";
$MESS["MAIN_AGENT_SORT"] = "الترتيب:";
$MESS["MAIN_AGENT_INTERVAL"] = "الفاصل الزمني (ثانية):";
$MESS["MAIN_AGENT_SAVE_BUTTON"] = "حفظ";
$MESS["MAIN_AGENT_START_EXEC"] = "تاريخ ووقت التشغيل التالي";
$MESS["MAIN_AGENT_EROR_NAME"] = "اسم الوكيل غير صحيح!";
$MESS["MAIN_AGENT_ERROR_SAVING"] = "خطأ!";
$MESS["MAIN_AGENT_RECORD_LIST"] = "قائمة الوكلاء";
$MESS["MAIN_AGENT_RECORD_LIST_TITLE"] = "الانتقال إلى قائمة الوكلاء";
$MESS["MAIN_AGENT_NEW_RECORD"] = "إضافة";
$MESS["MAIN_AGENT_NEW_RECORD_TITLE"] = "إضافة وكيل جديد";
$MESS["MAIN_AGENT_DEL_RECORD"] = "حذف";
$MESS["MAIN_AGENT_DEL_RECORD_TITLE"] = "حذف الوكيل";
$MESS["MAIN_AGENT_DELETE_RECORD_CONF"] = "هل أنت متأكد أنك تريد حذف هذا الوكيل؟";
$MESS["MAIN_AGENT_DEL_EXEC"] = "تم حذف الوكيل بعد تشغيل ناجح أو نتيجة خطأ!";
$MESS["MAIN_AGENT_PERIODICAL1"] = "تشغيل الوكيل:";
$MESS["MAIN_AGENT_PERIODICAL_INTERVAL"] = "بانتظام";
$MESS["MAIN_AGENT_PERIODICAL_TIME"] = "في وقت محدد";
?>